<?php
/* ══════════════════════════════════════════════════
   RENOV - Dados centralizados do site
   Edite este arquivo para alterar conteúdo de soluções e diferenciais
   ══════════════════════════════════════════════════ */

// ─── ÍCONES SVG PROFISSIONAIS (line-art monocromático) ───
$icons = [
  'folha' => '<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="10" y="4" width="28" height="40" rx="3"/><path d="M17 14h14M17 20h14M17 26h8"/><path d="M31 28l-4 4 8 8 4-4-8-8z"/></svg>',
  'esocial' => '<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="6" y="8" width="36" height="32" rx="3"/><path d="M6 16h36"/><circle cx="14" cy="12" r="1.5" fill="currentColor"/><circle cx="20" cy="12" r="1.5" fill="currentColor"/><circle cx="26" cy="12" r="1.5" fill="currentColor"/><path d="M14 24h6M14 30h10M14 36h8M30 24l3 3 6-6"/></svg>',
  'beneficios' => '<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="6" y="12" width="36" height="28" rx="3"/><path d="M6 20h36"/><path d="M14 28h4M14 34h8"/><circle cx="34" cy="32" r="6"/><path d="M34 29v6M31 32h6"/></svg>',
  'frequencia' => '<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="24" cy="24" r="18"/><path d="M24 12v12l8 5"/><path d="M4 24h4M40 24h4M24 4v4M24 40v4"/></svg>',
  'admissao' => '<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="20" cy="16" r="8"/><path d="M6 42c0-8 6-14 14-14s14 6 14 14"/><path d="M36 18h8M40 14v8"/></svg>',
  'ferias' => '<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="6" y="8" width="36" height="34" rx="3"/><path d="M6 18h36"/><path d="M16 4v8M32 4v8"/><path d="M14 26h4v4h-4zM22 26h4v4h-4zM30 26h4v4h-4zM14 34h4v4h-4zM22 34h4v4h-4z"/></svg>',
  'rescisoes' => '<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="8" y="4" width="24" height="36" rx="3"/><path d="M15 14h10M15 20h10M15 26h6"/><path d="M36 20v20a4 4 0 01-4 4H12"/><path d="M28 36l4 4 8-8"/></svg>',
  'contabil' => '<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="6" width="18" height="36" rx="2"/><rect x="26" y="6" width="18" height="36" rx="2"/><path d="M10 16h6M10 22h6M10 28h6"/><path d="M32 16h6M32 22h6M32 28h6"/><path d="M22 20l4 4M22 24l4-4"/></svg>',
  'workflows' => '<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="10" cy="12" r="6"/><circle cx="38" cy="12" r="6"/><circle cx="24" cy="36" r="6"/><path d="M14 16l8 14M34 16l-8 14"/><path d="M10 18v6l14 6M38 18v6l-14 6"/></svg>',
  'atendimento' => '<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M8 32V18a16 16 0 0132 0v14"/><path d="M8 28v8a4 4 0 004 4h2v-16h-2a4 4 0 00-4 4zM40 28v8a4 4 0 01-4 4h-2V24h2a4 4 0 014 4z"/><path d="M36 40c0 4-5 6-12 6"/></svg>',
  'analytics' => '<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="4" width="40" height="32" rx="3"/><path d="M4 12h40"/><path d="M12 20v10M20 22v8M28 18v12M36 24v6"/><path d="M16 40h16M24 36v4"/></svg>',
  'orcamento' => '<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="24" cy="24" r="18"/><path d="M24 12v24"/><path d="M18 18c0-3 2.7-4 6-4s6 1 6 4-2.7 3.5-6 4.5-6 1.5-6 4.5 2.7 4 6 4 6-1 6-4"/></svg>',
  'saneamento' => '<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M28.5 4.5l15 15-3 3-15-15z"/><path d="M24 9l-3.5 3.5L6 27l-2 13 13-2L31.5 23.5 35 20"/><path d="M18 30l-6 6"/><circle cx="7" cy="41" r="2" fill="currentColor"/></svg>',
  'legal' => '<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M24 4v36"/><path d="M10 40h28"/><path d="M8 16l16-8 16 8"/><path d="M12 16v10a4 4 0 004 4h0a4 4 0 004-4V16M28 16v10a4 4 0 004 4h0a4 4 0 004-4V16"/></svg>',
  'chatbot' => '<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="6" y="6" width="36" height="28" rx="4"/><path d="M18 38l-6 6v-6"/><path d="M16 18h4M28 18h4"/><path d="M18 26c2 2 4 3 6 3s4-1 6-3"/></svg>',
  'automacao' => '<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="12" y="8" width="24" height="20" rx="4"/><circle cx="20" cy="18" r="2.5"/><circle cx="28" cy="18" r="2.5"/><path d="M20 24h8"/><path d="M18 28v8M30 28v8"/><path d="M14 36h6M28 36h6"/><path d="M24 4v4"/></svg>',
];

$checkSvg = '<svg width="12" height="10" viewBox="0 0 12 10" fill="none"><path d="M1 5L4.5 8.5L11 1.5" stroke="#00c4ab" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>';

// ─── SOLUÇÕES ───
$solucoes = [
  'folha-de-pagamento' => ['icon'=>'folha','title'=>'Folha de Pagamento','subtitle'=>'Processamento com precisão financeira e conferência dupla via LG Lugar de Gen.te','text'=>'Nosso serviço de Folha de Pagamento cobre todo o ciclo mensal com rigor financeiro. Calculamos salários, horas extras, adicionais, insalubridade e periculosidade, além de todos os descontos legais e encargos sociais. Cada folha passa por conferência dupla antes do fechamento, garantindo precisão absoluta e eliminando retrabalho.','bullets'=>['Cálculo completo de salários e encargos sociais','Conferência dupla antes de cada fechamento','Geração de guias de recolhimento (FGTS, INSS, IRRF)','Integração nativa com LG Lugar de Gen.te (FPW e Suite Gen.te Nuvem)'],'detail'=>'Oferecemos uma solução completa que transforma a gestão de folha de pagamento em uma operação precisa e eficiente. Nossa equipe especializada se encarrega de todos os detalhes financeiros, desde o cálculo de salários e adicionais até a geração de guias de recolhimento e integração contábil. Utilizamos exclusivamente o sistema LG Lugar de Gen.te para garantir máxima rastreabilidade e conformidade.'],
  'esocial' => ['icon'=>'esocial','title'=>'eSocial e Obrigações','subtitle'=>'100% de compliance com zero multas e monitoramento contínuo','text'=>'Gerenciamos todas as obrigações acessórias do seu Departamento Pessoal. Envio de eventos ao eSocial, CAGED, RAIS, DIRF mensal, informes de rendimentos e DCTFWeb. Monitoramos cada prazo e validamos os dados antes do envio.','bullets'=>['Envio de todos os eventos eSocial (S-1000 a S-5012)','DIRF mensal, CAGED, RAIS e DCTFWeb','Monitoramento contínuo de prazos e retornos governamentais','Correção proativa de inconsistências antes de gerar multas'],'detail'=>'Manter o compliance com o eSocial e demais obrigações acessórias é uma tarefa complexa que exige atenção contínua aos prazos e às constantes mudanças na legislação. Nossa equipe monitora cada evento, valida os dados antes do envio e acompanha os retornos do governo para correção imediata de qualquer inconsistência.'],
  'gestao-de-beneficios' => ['icon'=>'beneficios','title'=>'Gestão de Benefícios','subtitle'=>'Auditoria de faturas, rateio por centro de custo e controle total','text'=>'Administramos vale transporte, vale refeição e alimentação, planos de saúde e odontológico, seguro de vida e demais benefícios. Auditoria de faturas, rateio por centro de custo e negociação com operadoras para otimização de custos.','bullets'=>['Auditoria de faturas e identificação de cobranças indevidas','Rateio automatizado por centro de custo e filial','Inclusão e exclusão de beneficiários sincronizada com a folha','Negociação com operadoras para otimização de custos'],'detail'=>'A gestão de benefícios vai muito além de incluir e excluir beneficiários. Realizamos auditoria mensal de todas as faturas para identificar cobranças indevidas, duplicidades e divergências cadastrais. O rateio por centro de custo é automatizado e integrado à contabilidade, dando visibilidade total ao CFO sobre o impacto financeiro de cada benefício.'],
  'gestao-de-frequencia' => ['icon'=>'frequencia','title'=>'Gestão de Frequência','subtitle'=>'Controle de ponto, banco de horas e conformidade com Portaria 671','text'=>'Realizamos o tratamento completo do ponto eletrônico. Importação de marcações, tratamento de inconsistências, gestão de justificativas, controle de banco de horas e escalas de turnos com integração automática com a folha.','bullets'=>['Importação e tratamento automatizado de marcações','Controle de banco de horas e escalas de turnos','Gestão de justificativas de faltas e atrasos','Conformidade com Portaria 671 e convenções coletivas'],'detail'=>'O tratamento de frequência é uma das operações mais sensíveis do DP, com impacto direto na folha de pagamento e nos custos de hora extra. Nossa equipe realiza o tratamento completo das marcações, identifica e resolve inconsistências, gerencia banco de horas e garante conformidade total com a Portaria 671.'],
  'admissao-digital' => ['icon'=>'admissao','title'=>'Admissão Digital','subtitle'=>'Processo admissional sem papel, com registro direto no LG','text'=>'Digitalizamos todo o processo admissional. O novo colaborador recebe um link para envio de documentos, preenchimento de dados cadastrais e assinatura digital do contrato. Qualificação cadastral, registro no LG e inclusão em benefícios.','bullets'=>['Processo 100% digital e sem papel','Qualificação cadastral automática junto ao eSocial','Registro direto no sistema LG Lugar de Gen.te','Inclusão em benefícios integrada ao fluxo admissional'],'detail'=>'O processo admissional tradicional consome horas de trabalho manual, gera erros cadastrais e atrasa o início produtivo do colaborador. Com a admissão digital da Renov, todo o fluxo acontece de forma automatizada, desde o envio de documentos até o registro final no sistema LG.'],
  'gestao-de-ferias' => ['icon'=>'ferias','title'=>'Gestão de Férias','subtitle'=>'Controle de períodos, cálculos e provisões com impacto financeiro','text'=>'Controlamos todos os períodos aquisitivos e concessivos. Alertas de vencimento, programação com gestores, cálculos com terço constitucional e projeção financeira de provisões.','bullets'=>['Controle de períodos aquisitivos e concessivos','Alertas automáticos de vencimento para gestores','Cálculo de terço constitucional e abono pecuniário','Projeção financeira de provisões de férias'],'detail'=>'A gestão de férias impacta diretamente o fluxo de caixa e as provisões contábeis da empresa. Controlamos cada período aquisitivo, enviamos alertas antes do vencimento, organizamos a programação com os gestores e calculamos todos os valores com precisão.'],
  'rescisoes' => ['icon'=>'rescisoes','title'=>'Rescisões','subtitle'=>'Cálculos precisos, documentação completa e mitigação de riscos','text'=>'Cálculos rescisórios conferidos e auditados. Saldo de salário, aviso prévio, décimo terceiro, férias, multa de 40% do FGTS. Documentação completa para homologação e análise de risco trabalhista.','bullets'=>['Cálculos rescisórios conferidos e auditados','Documentação completa para homologação','Geração de GRRF e guias de recolhimento','Análise de risco trabalhista em cada desligamento'],'detail'=>'Cada rescisão é uma oportunidade de passivo trabalhista se não for executada com precisão. Nossa equipe realiza todos os cálculos com conferência dupla, prepara a documentação completa e analisa o risco jurídico de cada desligamento antes da formalização.'],
  'integracao-contabil' => ['icon'=>'contabil','title'=>'Integração Contábil','subtitle'=>'Exportação automatizada com rateio por centro de custo e filial','text'=>'Geramos arquivos de integração contábil no layout do seu ERP, com rateio por centro de custo, conta contábil e filial. Exportação automatizada e totalmente auditável.','bullets'=>['Exportação no layout do seu ERP','Rateio automático por centro de custo e filial','Processo automatizado e auditável','Rastreabilidade total dos lançamentos contábeis'],'detail'=>'A integração contábil é o elo entre o DP e o financeiro. Geramos os arquivos no exato layout do seu ERP ou sistema contábil, com rateio detalhado por centro de custo, conta contábil e filial. Todo o processo é automatizado e auditável.'],
  'workflows-automatizados' => ['icon'=>'workflows','title'=>'Workflows Automatizados','subtitle'=>'Fluxos inteligentes que eliminam trabalho manual e erros operacionais','text'=>'Aprovação de férias, solicitação de benefícios, movimentações de pessoal, relatórios periódicos e alertas de compliance. Tudo automatizado para eliminar erros e ganhar velocidade.','bullets'=>['Aprovação automatizada de férias e benefícios','Alertas de compliance e prazos regulatórios','Movimentações de pessoal sem papel','Relatórios gerenciais gerados automaticamente'],'detail'=>'Processos manuais são lentos, propensos a erros e difíceis de auditar. Implementamos workflows automatizados para cada processo crítico do DP, garantindo que aprovações, notificações e relatórios aconteçam de forma automática e rastreável.'],
  'atendimento-dedicado' => ['icon'=>'atendimento','title'=>'Atendimento Dedicado','subtitle'=>'Equipe exclusiva com SLA contratual e reuniões periódicas','text'=>'Equipe dedicada que conhece profundamente a sua operação. Canais diretos de comunicação com SLA de resposta definido em contrato e reuniões periódicas com indicadores.','bullets'=>['Equipe exclusiva para a sua empresa','Canais diretos: WhatsApp, email e telefone','SLA de resposta definido em contrato','Reuniões periódicas com apresentação de indicadores'],'detail'=>'Na Renov, cada cliente conta com uma equipe dedicada que conhece cada detalhe da sua operação. Não existe fila de atendimento genérica. Você fala direto com quem resolve, com SLA de resposta garantido em contrato e reuniões periódicas onde apresentamos indicadores e identificamos oportunidades de melhoria.'],
];

// ─── DIFERENCIAIS ───
$diferenciais = [
  'people-analytics' => ['icon'=>'analytics','title'=>'People Analytics','subtitle'=>'Cockpit de BI em tempo real com conexão direta via API','text'=>'Oferecemos um cockpit de Business Intelligence em tempo real, com conexão direta via API ao sistema LG Lugar de Gen.te. Os indicadores financeiros do seu Departamento Pessoal estão sempre atualizados e prontos para embasar decisões executivas.','bullets'=>['Dashboards financeiros em tempo real via conexão API','Custo de folha por departamento, filial e centro de custo','Indicadores de headcount, turnover e absenteísmo atualizados automaticamente','Provisões de férias e décimo terceiro com impacto financeiro visível'],'detail'=>'Nosso People Analytics vai muito além de relatórios estáticos. Com conexão direta via API ao sistema LG Lugar de Gen.te, os dados são atualizados automaticamente e apresentados em dashboards interativos que permitem à diretoria tomar decisões baseadas em dados reais do DP.'],
  'gestao-orcamentaria' => ['icon'=>'orcamento','title'=>'Gestão Orçamentária','subtitle'=>'Controle financeiro do DP com projeção e análise de desvios','text'=>'Projetamos custos de folha, encargos, benefícios e provisões para que o financeiro e a diretoria tenham visibilidade total do impacto da força de trabalho no resultado da empresa.','bullets'=>['Projeção de custos de folha e encargos sociais','Comparativo orçado versus realizado mensal','Simulação de cenários para novas contratações e reestruturações','Relatórios financeiros integrados com a contabilidade'],'detail'=>'O orçamento do DP é uma das maiores linhas de custo de qualquer empresa. Nossa gestão orçamentária projeta custos, compara orçado versus realizado mês a mês e identifica desvios antes que impactem o resultado financeiro.'],
  'saneamento-e-parametrizacao' => ['icon'=>'saneamento','title'=>'Saneamento e Parametrização Sistêmica','subtitle'=>'Sistema LG configurado com precisão cirúrgica para a sua operação','text'=>'Saneamento completo da base de dados e parametrização do sistema LG Lugar de Gen.te. Corrigimos cadastros, ajustamos regras de cálculo e configuramos eventos e rubricas conforme as convenções coletivas.','bullets'=>['Auditoria e limpeza de cadastros inconsistentes','Parametrização de eventos, rubricas e tabelas','Configuração conforme convenções coletivas','Sistema LG otimizado para máxima performance e precisão'],'detail'=>'Um sistema mal parametrizado gera erros silenciosos que se acumulam e explodem em passivos trabalhistas e fiscais. Realizamos o saneamento completo da base de dados e a parametrização cirúrgica do LG Lugar de Gen.te.'],
  'legal-preventivo' => ['icon'=>'legal','title'=>'Legal Preventivo','subtitle'=>'Identifique riscos trabalhistas antes que virem passivos financeiros','text'=>'Identificação antecipada de riscos trabalhistas na operação do DP. Analisamos processos e documentações para encontrar vulnerabilidades antes que se transformem em reclamações ou autuações.','bullets'=>['Auditoria preventiva de processos e documentações','Identificação de vulnerabilidades com impacto financeiro','Recomendações práticas de correção com priorização por risco','Parceria com escritórios especializados em direito do trabalho'],'detail'=>'Cada processo do DP carrega risco trabalhista potencial. Nosso serviço de Legal Preventivo analisa documentações, práticas e fluxos para identificar vulnerabilidades antes que se transformem em reclamações ou autuações fiscais.'],
  'chatbot-whatsapp' => ['icon'=>'chatbot','title'=>'ChatBot de WhatsApp para Colaboradores','subtitle'=>'Autoatendimento inteligente que reduz custo operacional do RH','text'=>'Chatbot de WhatsApp para atendimento dos colaboradores. Respostas sobre holerite, férias, benefícios e documentos de forma instantânea, 24 horas, sem sobrecarregar a equipe.','bullets'=>['Autoatendimento 24 horas via WhatsApp','Respostas sobre holerite, férias, benefícios e documentos','Chatbot treinado com as regras e políticas da sua empresa','Redução drástica do volume de chamados repetitivos'],'detail'=>'Cada chamado repetitivo que o RH atende manualmente é custo operacional desperdiçado. Nosso chatbot de WhatsApp responde automaticamente às dúvidas mais frequentes dos colaboradores, liberando a equipe para atividades de maior valor.'],
  'automacao-n8n' => ['icon'=>'automacao','title'=>'Automação com N8N','subtitle'=>'Integração entre sistemas que elimina trabalho manual e erros','text'=>'Automações inteligentes via N8N que conectam os sistemas do DP e eliminam tarefas manuais. A informação certa chega no lugar certo, no momento certo, sem intervenção humana.','bullets'=>['Automações personalizadas para a sua operação','Integração entre LG, ERP, contabilidade e outros sistemas','Alertas automáticos de compliance e prazos','Eliminação de tarefas manuais com redução comprovada de erros'],'detail'=>'A plataforma N8N nos permite criar automações sofisticadas que conectam o LG Lugar de Gen.te com qualquer outro sistema da sua empresa. Desde alertas automáticos de prazos até integrações complexas entre ERP, contabilidade e DP.'],
];
